<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- Analyzers -->
    <PackageVersion Include="Meziantou.Analyzer" Version="3.0.257" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.34.0.3385" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.16.1" />
    <PackageVersion Include="AsyncFixer" Version="2.1.0" />

    <!-- Source Generator -->
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />

    <!-- SourceLink -->
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />

    <!-- Testing -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageVersion Include="TUnit" Version="1.67.0" />

    <!-- Testing - Source Generator -->
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.9.0" />
    <PackageVersion Include="Basic.Reference.Assemblies.Net80" Version="1.8.11" />
  </ItemGroup>
</Project>