using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace SimpleBranchVersioning;

/// <summary>
/// Source generator that creates an AppVersion class with version information from git.
/// </summary>
[Generator]
public sealed class AppVersionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Get git info and root namespace from MSBuild properties
        var buildPropertiesProvider = context.AnalyzerConfigOptionsProvider
            .Select((provider, _) =>
            {
                provider.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);
                provider.GlobalOptions.TryGetValue("build_property.SimpleBranchVersioning_Branch", out var branch);
                provider.GlobalOptions.TryGetValue("build_property.SimpleBranchVersioning_CommitId", out var commitId);
                return new BuildProperties(rootNamespace, branch, commitId);
            });

        // Look for AppVersionConfigAttribute in assembly attributes
        var configAttributeProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "SimpleBranchVersioning.AppVersionConfigAttribute",
                predicate: static (node, _) => node is CompilationUnitSyntax,
                transform: static (ctx, _) => GetConfigFromAttribute(ctx))
            .Collect()
            .Select((configs, _) => configs.IsDefaultOrEmpty ? null : configs[0]);

        // Combine all the inputs
        var combined = buildPropertiesProvider.Combine(configAttributeProvider);

        // Register the source output
        context.RegisterSourceOutput(combined, static (ctx, input) =>
        {
            var (buildProps, config) = input;

            var branch = string.IsNullOrEmpty(buildProps.Branch) ? "unknown" : buildProps.Branch!;
            var commitId = string.IsNullOrEmpty(buildProps.CommitId) ? "0000000" : buildProps.CommitId!;
            var version = VersionCalculator.Calculate(branch, commitId);
            var namespaceName = config?.Namespace ?? buildProps.RootNamespace ?? "SimpleBranchVersioning.Generated";
            var className = config?.ClassName ?? "AppVersion";

            var source = GenerateSource(namespaceName, className, version, branch, commitId);
            ctx.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static AppVersionConfig? GetConfigFromAttribute(GeneratorAttributeSyntaxContext context)
    {
        var attribute = context.Attributes.FirstOrDefault();
        if (attribute is null)
            return null;

        string? namespaceName = null;
        string? className = null;

        foreach (var arg in attribute.NamedArguments)
        {
            switch (arg.Key)
            {
                case "Namespace":
                    namespaceName = arg.Value.Value as string;
                    break;
                case "ClassName":
                    className = arg.Value.Value as string;
                    break;
            }
        }

        return new AppVersionConfig(namespaceName, className);
    }

    private static string GenerateSource(string namespaceName, string className, string version, string branch, string commitId)
    {
        return $@"// <auto-generated/>
#nullable enable

namespace {namespaceName}
{{
    /// <summary>
    /// Contains version information generated from git.
    /// </summary>
    public static class {className}
    {{
        /// <summary>
        /// The full version string.
        /// </summary>
        public const string Version = ""{version}"";

        /// <summary>
        /// The git branch name.
        /// </summary>
        public const string Branch = ""{branch}"";

        /// <summary>
        /// The short git commit ID.
        /// </summary>
        public const string CommitId = ""{commitId}"";
    }}
}}";
    }

    private sealed record BuildProperties(string? RootNamespace, string? Branch, string? CommitId);
    private sealed record AppVersionConfig(string? Namespace, string? ClassName);
}
